# Site settings
title: The Blog of Zhang Yu
email: feiyuw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A man can't just sit around!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.zhangyu.so" # the base hostname & protocol for your site
twitter_username: feiyuw
github_username:  feiyuw
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-paginate
